"""
navigation.py — Helpers for locating and extracting code from IDA Pro.
"""

import re

import idc
import idaapi
import idautils
import ida_funcs
import ida_hexrays
import ida_bytes

try:
    import ida_xref  # IDA 9.x
except ImportError:  # IDA 8.x kept these constants in idaapi.
    class _LegacyXrefTypes:
        fl_F = idaapi.fl_F
        fl_CN = idaapi.fl_CN
        fl_CF = idaapi.fl_CF
        fl_JN = idaapi.fl_JN
        fl_JF = idaapi.fl_JF

    ida_xref = _LegacyXrefTypes()

from ..config import PLUGIN_NAME, HEXRAYS_AVAILABLE


def get_current_function_ea() -> int | None:
    ea   = idc.get_screen_ea()
    func = ida_funcs.get_func(ea)
    return func.start_ea if func else None


def get_function_name(ea: int) -> str:
    name = idc.get_func_name(ea)
    return name if name else f"sub_{ea:X}"


def is_autogenerated_name(name: str) -> bool:
    return bool(re.match(
        r"^(sub|loc|nullsub|j_sub|_?unknown)_[0-9A-Fa-f]+$", name
    ))


_AUTOGEN_PREFIXES = ("nullsub_", "j_sub_", "sub_", "loc_")


def pdb_symbols_loaded() -> bool:
    """Heuristic: return True when IDA appears to have rich source symbols.

    IDA does not expose a single reliable "PDB loaded" boolean across versions.
    What matters for this pipeline is whether function symbols are rich enough
    that Codex-directed reconstruction can skip the LLM description pass and
    rely on names plus exact pseudocode.  MSVC-decorated names, C++ scope names,
    and a high ratio of user/real names are strong signals.
    """
    try:
        total = 0
        named = 0
        strong = 0
        user_named = 0

        for ea in idautils.Functions():
            total += 1
            name = get_function_name(ea) or ""
            lower = name.lower()
            if (
                not name
                or is_autogenerated_name(name)
                or lower.startswith(("sub_", "loc_", "nullsub_", "j_sub_", "unknown_libname_"))
            ):
                continue

            named += 1
            if name.startswith("?") or "::" in name or "@@" in name or re.search(r"@[A-Za-z_][A-Za-z0-9_]*@@", name):
                strong += 1

            try:
                flags = idc.get_full_flags(ea)
                if hasattr(idc, "has_user_name") and idc.has_user_name(flags):
                    user_named += 1
            except Exception:
                pass

        if total < 10:
            return False

        named_ratio = named / total
        user_ratio = user_named / total

        return (
            (strong >= 50 and named_ratio >= 0.20)
            or (named >= 100 and named_ratio >= 0.60)
            or (user_named >= 50 and user_ratio >= 0.30)
        )
    except Exception:
        return False

def find_function_by_name(name: str) -> int | None:
    """Look up a function EA by name.

    Handles the common race: a sibling goroutine may have already renamed
    e.g. sub_1400014B0 to something descriptive. In that case
    get_name_ea_simple returns BADADDR, but the original EA is still
    encoded in the autogenerated-name suffix — we recover it directly.
    """
    ea = idc.get_name_ea_simple(name)
    if ea != idaapi.BADADDR:
        return ea

    # EA-from-name fallback — only for autogenerated names whose address
    # is encoded as a hex suffix (sub_XXXX, loc_XXXX, nullsub_XXXX, j_sub_XXXX).
    lower = name.lower()
    for prefix in _AUTOGEN_PREFIXES:
        if lower.startswith(prefix):
            hex_part = name[len(prefix):]
            try:
                candidate = int(hex_part, 16)
                fn = ida_funcs.get_func(candidate)
                # Must be the start of a function, not an interior address.
                if fn is not None and fn.start_ea == candidate:
                    return candidate
            except ValueError:
                pass
            break  # matched prefix, no point trying others

    return None


def get_pseudocode(ea: int) -> str | None:
    if not HEXRAYS_AVAILABLE:
        return None
    try:
        cfunc = ida_hexrays.decompile(ea)
        return str(cfunc) if cfunc else None
    except Exception as e:
        print(f"[{PLUGIN_NAME}] Decompile error @ {ea:#x}: {e}")
        return None


def get_disassembly(ea: int) -> str:
    lines = []
    for item_ea in idautils.FuncItems(ea):
        lines.append(f"{item_ea:#010x}  {idc.generate_disasm_line(item_ea, 0)}")
    return "\n".join(lines)


def get_function_code(ea: int) -> str:
    code = get_pseudocode(ea)
    return code if code else get_disassembly(ea)


def get_function_global_references(ea: int) -> list:
    references = {}
    for item_ea in idautils.FuncItems(ea):
        for target_ea in idautils.DataRefsFrom(item_ea):
            if ida_funcs.get_func(target_ea) is not None:
                continue
            item_head = ida_bytes.get_item_head(target_ea)
            symbol_ea = target_ea
            name = idc.get_name(symbol_ea) or ""
            if not name:
                symbol_ea = item_head
                name = idc.get_name(symbol_ea) or ""
            if not name:
                continue
            try:
                if ida_bytes.is_strlit(ida_bytes.get_flags(item_head)):
                    continue
            except (AttributeError, TypeError):
                pass
            references[symbol_ea] = {
                "name": name,
                "address": hex(symbol_ea),
            }
    return [references[symbol_ea] for symbol_ea in sorted(references)]


def scan_exports() -> list:
    """Return exported functions from the current module.

    IDA exposes PE exports through idautils.Entries().  For source
    reconstruction these are independent public entry points, not children of
    DllMain, so the server treats each exported function as an additional call
    tree root.
    """
    exports = []
    try:
        for _idx, ordinal, ea, name in idautils.Entries():
            if ea == idaapi.BADADDR:
                continue
            fn = ida_funcs.get_func(ea)
            start = fn.start_ea if fn else ea
            exports.append({
                "ea": hex(start),
                "name": name or "",
                "function_name": get_function_name(start) if fn else (idc.get_name(ea) or ""),
                "ordinal": int(ordinal) if ordinal is not None else 0,
                "is_function": bool(fn),
            })
    except Exception as e:
        print(f"[{PLUGIN_NAME}] Export scan error: {e}")
    return sorted(exports, key=lambda ex: (ex.get("ea", ""), ex.get("ordinal", 0), ex.get("name", "")))


# Code xref types that represent a true direct call or jump.
# fl_U ("used" / address-taken) is intentionally excluded — those are callbacks,
# handled by get_referenced_callback_eas and listed separately.
# IDA 9.x: these constants moved from idaapi to ida_xref.
_CALL_TYPES = frozenset({ida_xref.fl_CN, ida_xref.fl_CF, ida_xref.fl_JN, ida_xref.fl_JF})


def get_called_function_eas(ea: int) -> list:
    """Return EAs of functions directly CALLED or JMPed to from ea.

    Uses XrefsFrom filtered to fl_CN/fl_CF/fl_JN/fl_JF only.  CodeRefsFrom
    also returns fl_U (address-taken) refs, which would wrongly include
    callbacks like (LPTHREAD_START_ROUTINE)Entry in the direct-callee list and
    cause them to appear as child nodes rather than separate trees.
    """
    called = set()
    for item_ea in idautils.FuncItems(ea):
        for xref in idautils.XrefsFrom(item_ea, False):
            if xref.type not in _CALL_TYPES:
                continue
            tgt = ida_funcs.get_func(xref.to)
            if tgt and tgt.start_ea != ea:
                called.add(tgt.start_ea)
    return list(called)


# Xref types that represent direct control transfer — NOT address-taken callbacks.
# fl_F  = ordinary flow (fall-through)
# fl_CN = near call, fl_CF = far call
# fl_JN = near jump,  fl_JF = far jump
# IDA 9.x: constants moved from idaapi to ida_xref.
_DIRECT_FLOW_TYPES = frozenset({
    ida_xref.fl_F,
    ida_xref.fl_CN, ida_xref.fl_CF,
    ida_xref.fl_JN, ida_xref.fl_JF,
})


def get_referenced_callback_eas(ea: int) -> list:
    """Find every function whose address is referenced inside `ea`.

    Covers three cases:

      1. Direct address-taken in code — `lea rcx, Entry`, `push offset fn`,
         `mov rdx, offset fn`.  IDA emits fl_U (used) code xrefs or dr_O data
         xrefs for these; both are caught by XrefsFrom.

      2. Inline data inside the function — jump tables, dispatch tables, and
         other data items embedded in the function's address range.  FuncItems
         skips these; we use Chunks+Heads to cover ALL defined items (code and
         data) across every chunk of the function.

      3. Function pointer tables in a separate data section — the function
         holds a data ref to a table address; the table itself holds data refs
         to the actual functions.  We follow data references one level deep to
         catch this pattern (e.g. a handler table in .rdata loaded via LEA).
    """
    f = ida_funcs.get_func(ea)
    if not f:
        return []

    callbacks = set()
    data_to_follow = set()   # non-function data items referenced from code

    # Pass 1: every item in every chunk of the function.
    for chunk_start, chunk_end in idautils.Chunks(ea):
        for item_ea in idautils.Heads(chunk_start, chunk_end):
            for xref in idautils.XrefsFrom(item_ea, False):
                if xref.type in _DIRECT_FLOW_TYPES:
                    continue
                tgt = ida_funcs.get_func(xref.to)
                if tgt and tgt.start_ea == xref.to and tgt.start_ea != ea:
                    callbacks.add(tgt.start_ea)
                elif not xref.iscode and not tgt:
                    # Data ref to a non-function address — may be a table.
                    data_to_follow.add(xref.to)

    # Pass 2: follow data refs one level deep to catch .rdata function tables.
    for data_ea in data_to_follow:
        for xref in idautils.XrefsFrom(data_ea, False):
            tgt = ida_funcs.get_func(xref.to)
            if tgt and tgt.start_ea == xref.to and tgt.start_ea != ea:
                callbacks.add(tgt.start_ea)

    return list(callbacks)


def function_has_virtual_calls(ea: int) -> bool:
    """Heuristic detection of virtual/indirect calls inside a function.

    Walks each instruction's first operand looking for indirect call/jmp
    forms (memory-indirect or register-indirect calls). Direct calls to
    a resolved function are NOT flagged.
    """
    try:
        for item_ea in idautils.FuncItems(ea):
            mnem = (idc.print_insn_mnem(item_ea) or "").lower()
            if mnem not in ("call", "jmp"):
                continue
            op_type = idc.get_operand_type(item_ea, 0)
            # 1 = register, 3 = memory phrase [reg+reg], 4 = memory displacement,
            # 6 = far function pointer, 7 = near function pointer (direct).
            # Indirect-through-register/memory means virtual or function-pointer
            # call rather than a direct symbol reference.
            if op_type in (1, 3, 4):
                # If a CodeRef resolves it, it's a direct call we already track.
                refs = [r for r in idautils.CodeRefsFrom(item_ea, False)]
                if not refs:
                    return True
                # Has a code ref but the operand is register/memory — still
                # treat as virtual (e.g. vtable dispatch where the offset is
                # known but the dispatch is through a pointer).
                if op_type in (3, 4):
                    return True
    except Exception:
        pass
    return False


def is_import_or_thunk(ea: int) -> tuple[bool, bool]:
    """Returns (is_import, is_library_thunk) for a function EA.

    Detection strategy (in order):
      1. IDA FUNC_LIB flag with no decompilable body  → is_import
      2. IDA FUNC_LIB | FUNC_THUNK flags              → is_library
      3. Single-instruction JMP whose data reference
         resolves to an IAT entry (__imp_xxx)          → is_library
         This catches the extremely common pattern:
           strcmp  proc near
             jmp  cs:__imp_strcmp
           strcmp  endp
         where IDA assigns a real name and neither
         FUNC_LIB nor FUNC_THUNK is set.
    """
    try:
        f = ida_funcs.get_func(ea)
        if not f:
            return (False, False)

        # --- IDA flag checks ---
        # Avoid calling get_pseudocode here — decompiling solely to check
        # whether a body exists is expensive (1 full decompile per FUNC_LIB
        # function, fired during call-tree building before any LLM work).
        # Instead use the instruction count: a genuine import stub has no
        # real body (0 items) or is just a short trampoline.  FUNC_LIB with
        # no instructions → import; FUNC_LIB | FUNC_THUNK → library thunk.
        # IDA 9.x: FUNC_LIB / FUNC_THUNK moved from idc to ida_funcs.
        items = list(idautils.FuncItems(ea))
        has_body  = len(items) > 0
        is_import = bool(f.flags & ida_funcs.FUNC_LIB) and not has_body
        is_lib    = bool(f.flags & (ida_funcs.FUNC_LIB | ida_funcs.FUNC_THUNK))
        if is_import or is_lib:
            return (is_import, is_lib)

        # --- JMP-to-IAT pattern ---
        # A single JMP instruction whose only data reference points to a
        # slot named __imp_xxx is a pure import forwarder regardless of flags.
        if len(items) == 1:
            mnem = (idc.print_insn_mnem(items[0]) or "").lower()
            if mnem == "jmp":
                # Data refs from the JMP instruction give the IAT slot address.
                for ref in idautils.DataRefsFrom(items[0]):
                    ref_name = idc.get_name(ref) or ""
                    if "__imp_" in ref_name or ref_name.startswith(".imp"):
                        return (False, True)
                # Fallback: operand value directly (direct JMP form).
                target = idc.get_operand_value(items[0], 0)
                if target != idaapi.BADADDR:
                    target_name = idc.get_name(target) or ""
                    if "__imp_" in target_name or target_name.startswith(".imp"):
                        return (False, True)

        return (False, False)
    except Exception:
        return (False, False)


def build_call_tree(root_ea: int) -> dict:
    """Walk the full call graph reachable from root_ea (BFS) and return a
    map { ea_hex: {ea, name, callees, callbacks, is_import, is_library, has_virtual_calls} }.

    "callees" are functions reached by a direct CALL/JMP. "callbacks" are
    functions whose address is taken inside this function (registered as a
    handler, stored in a function-pointer table, passed to atexit/qsort/etc.) —
    detected statically via data cross-references, with no LLM involvement.

    Callbacks are folded into the traversal so each one — and its entire
    subtree — becomes part of the reachable graph and is analysed bottom-up,
    exactly as if it had started its own call chain. They are ALSO listed
    separately in the "callbacks" field so downstream consumers can tell an
    indirectly-invoked handler apart from a directly-called function.

    Cycles are handled by the visited set. Each function is described once;
    duplicates reached again are not re-added but their callers still list them.
    """
    out: dict = {}
    queue: list = [root_ea]
    visited: set = set()

    while queue:
        ea = queue.pop(0)
        if ea in visited:
            continue
        visited.add(ea)

        f = ida_funcs.get_func(ea)
        if not f:
            continue
        ea = f.start_ea  # normalise to function start

        if hex(ea) in out:
            continue

        name = get_function_name(ea)
        is_imp, is_lib = is_import_or_thunk(ea)
        if is_imp:
            direct_eas, callback_eas = [], []
        else:
            direct_eas = get_called_function_eas(ea)
            callback_eas = get_referenced_callback_eas(ea)
        has_virt = function_has_virtual_calls(ea) if not is_imp else False

        # callees = direct calls ∪ callbacks — callbacks appear as children of
        # the function that takes their address, exactly like regular callees.
        # callbacks field is kept so callers can identify which edges are
        # address-taken vs direct, but both appear in the same tree.
        reachable = set(direct_eas) | set(callback_eas)

        out[hex(ea)] = {
            "ea": hex(ea),
            "name": name,
            "callees":   [hex(c) for c in reachable],
            "is_import": is_imp,
            "is_library": is_lib,
            "has_virtual_calls": has_virt,
        }

        for c in reachable:
            if c not in visited:
                queue.append(c)

    return out


def get_bytes(ea: int, size: int) -> bytes | None:
    try:
        data = ida_bytes.get_bytes(ea, size)
        return data if data else None
    except Exception:
        return None


def find_string_xrefs(query: str, limit: int = 5) -> list:
    """Find binary strings containing `query` and the functions referencing them.

    Used by the server's pivot stage: when the call tree is exhausted but an
    objective is unanswered, the model proposes distinctive substrings (an error
    message, a format string, a protocol token) likely to sit near the relevant
    code. We match those against IDA's string list (case-insensitive substring),
    then walk data xrefs from each match back to the containing functions, so the
    engine can seed those functions as fresh analysis roots.

    Returns a list of {text, address, func_eas} dicts, at most `limit` strings.
    """
    if not query:
        return []
    if limit <= 0:
        limit = 5

    needle = query.lower()
    results: list = []

    try:
        for s in idautils.Strings():
            if len(results) >= limit:
                break
            try:
                text = str(s)
            except Exception:
                continue
            if needle not in text.lower():
                continue

            func_eas: set = set()
            for ref in idautils.XrefsTo(s.ea, False):
                fn = ida_funcs.get_func(ref.frm)
                if fn:
                    func_eas.add(fn.start_ea)

            if not func_eas:
                continue

            results.append({
                "text":     text[:200],
                "address":  hex(s.ea),
                "func_eas": [hex(ea) for ea in sorted(func_eas)],
            })
    except Exception as e:
        print(f"[{PLUGIN_NAME}] find_string_xrefs {query!r}: {e}")

    return results
